CREATE SCHEMA netpix;

CREATE TABLE netpix.users (
id UUID PRIMARY KEY,
username VARCHAR(30) UNIQUE,
password_hash TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE netpix.movies (
id SERIAL PRIMARY KEY,
user_id UUID NOT NULL REFERENCES netpix.users(id) ON DELETE CASCADE,
movie_id INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
